version: '3.9'
services:
  web:
    image: ideonvn-web
    build: ./web
    stop_grace_period: 10s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout:  5s
      retries: 3
      start_period: 15s
  nginx:
    image: ideonvn-nginx
    build: ./nginx
    ports:
      - 1994:80
    depends_on:
      - web
    restart: always
